name: build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64", "x86_64"]
        libc: ["gnu", "musl"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set rustup toolchain
        run: rustup default stable
      - name: Build
        run: cargo build --target ${{matrix.arch}}-unknown-linux-$${{matrix.libc}}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: cargo test --workspace

